#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# Only the part after the first dash is displayed

for file in *
do
    if [ -f "$file" ] && [[ $file != .* ]]
    then
        echo "$file" | cut -d '-' -f 2-
    fi
done
